# Generated by Django 5.1.3 on 2025-06-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='type',
            field=models.CharField(choices=[('t_shirt', 'T_shirt'), ('pant', 'pant')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('t_shirt', 'T_shirt'), ('pant', 'Pant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('t_shirt', 'T_shirt'), ('pant', 'Pant')], max_length=50),
        ),
    ]
