# Generated by Django 5.1.3 on 2025-07-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
