# Generated by Django 5.1.3 on 2025-07-19 20:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0002_alter_itemtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e_store.itemtype'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='type',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Only lowercase letters are allowed.')]),
        ),
    ]
