# Generated by Django 5.1.3 on 2025-07-20 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0003_alter_display_type_alter_itemtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='type',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator('^[a-z-]*$', 'Only lowercase letters are allowed.')]),
        ),
    ]
