# Generated by Django 5.1.3 on 2025-07-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0004_alter_itemtype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='type',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='name',
            field=models.CharField(default='pant', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
