# Generated by Django 5.1.3 on 2025-07-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0004_alter_display_image_alter_orderitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_store.inventory'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_store.item'),
        ),
        migrations.AlterField(
            model_name='display',
            name='image',
            field=models.ImageField(upload_to='display_category/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
