# Generated by Django 5.1.3 on 2025-07-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0005_remove_itemtype_type_itemtype_name_itemtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
