# Generated by Django 5.1.3 on 2025-07-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0005_rename_name_orderitem_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='inventory',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='type',
            field=models.CharField(default='t_shirt', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('t_shirt', 'T_shirt'), ('pant', 'Pant')], max_length=20),
        ),
    ]
