# Generated by Django 5.1.3 on 2025-07-04 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0006_remove_orderitem_inventory_orderitem_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_store.inventory'),
        ),
    ]
