# Generated by Django 5.1.3 on 2025-07-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0006_display_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtype',
            old_name='name',
            new_name='type',
        ),
    ]
