# Generated by Django 5.1.3 on 2025-07-07 07:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0007_remove_orderitem_size_remove_orderitem_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('t_shirt', 'T_shirt'), ('pant', 'Pant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('printing', 'Printing in Progress & Decrease inventory'), ('shipped', 'Shipped & Notifie customer'), ('delivered', 'Delivered & Notifie customer'), ('canceled', 'Canceled & Notifie customer'), ('delivery refused', 'Delivery refused')], max_length=20),
        ),
    ]
