# Generated by Django 5.1.3 on 2025-07-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0007_rename_name_itemtype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='slug',
        ),
    ]
