# Generated by Django 5.1.3 on 2025-07-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0008_remove_display_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
