# Generated by Django 5.1.3 on 2025-07-27 13:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0010_size_alter_inventory_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
