# Generated by Django 5.1.3 on 2025-07-07 16:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0013_alter_display_image_alter_item_image_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('t_shirt', 'T_shirt'), ('pant', 'Pant')], max_length=50),
        ),
    ]
