# Generated by Django 5.1.3 on 2025-07-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0014_alter_display_image_alter_item_image_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='image',
            field=models.ImageField(upload_to='display_category/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('t_shirt', 'T_shirt'), ('pant', 'Pant')], max_length=20),
        ),
    ]
