# Generated by Django 5.1.3 on 2025-10-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0014_alter_display_image_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('printing', 'Printing in Progress & Decrease inventory'), ('shipped', 'Shipped & Notifie customer'), ('delivered', 'Delivered & Notifie customer'), ('cancelled', 'Canceled & Notifie customer'), ('delivery refused', 'Delivery refused')], max_length=20),
        ),
    ]
