# Generated by Django 5.1.3 on 2025-10-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0024_alter_display_image_alter_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('printing', 'Printing in Progress & Decrease inventory'), ('shipped', 'Shipped & Notify customer'), ('delivered', 'Delivered & Notify customer'), ('cancelled', 'Cancelled & Notify customer'), ('delivery refused', 'Delivery refused')], max_length=20),
        ),
    ]
