# Generated by Django 5.1.3 on 2025-10-22 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0025_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid name. Only letters, spaces, hyphens, and apostrophes are allowed.', regex="^[A-Za-zÀ-ÖØ-öø-ÿ '-]+$")], verbose_name='Last_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('printing', 'Printing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('delivery refused', 'Delivery')], max_length=20),
        ),
    ]
