# Generated by Django 5.1.3 on 2025-10-24 08:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0026_alter_order_last_name_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
