# Generated by Django 5.1.3 on 2025-12-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0029_alter_display_image_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='image',
            field=models.ImageField(max_length=200, upload_to='display/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(max_length=200, upload_to='item/'),
        ),
    ]
